root: true

plugins:
    - "@typescript-eslint"
    - astro
    - import
    - turbo
    - prettier

parser: "@typescript-eslint/parser"

parserOptions:
    project: true

extends:
    - eslint:recommended
    - plugin:@typescript-eslint/strict
    - plugin:astro/recommended
    - plugin:import/recommended
    - plugin:import/typescript
    - plugin:prettier/recommended

settings:
    import/resolver:
        typescript: true

overrides:
    - files:
          - "*.astro"
      parser: "astro-eslint-parser"
      parserOptions:
          parser: "@typescript-eslint/parser"
          extraFileExtensions:
              - .astro

env:
    node: true
    browser: true

rules:
    prettier/prettier:
        - error
